source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 3.0'
pod 'SnapKit', '~> 0.15.0'
pod "PKHUD"
pod 'FMDB', '~> 2.5'
pod 'SWXMLHash', '~> 2.0.0'
pod 'Fuzi', '~> 0.2.0'

